language: java

services:
  - mysql

before_script:
  - mysql -u root -e 'CREATE DATABASE productsDB;'
  - mysql -u root -e "CREATE USER 'spq'@'localhost' IDENTIFIED BY 'spq';"
  - mysql -u root -e "GRANT ALL ON productsDB.* TO 'spq'@'localhost';"
