language: java

services:
  - xfvb
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE gestion_biblioteca_db;'
  
  - mysql -u root -e "GRANT ALL ON gestion_biblioteca_db.* TO 'root'@'localhost';"
